### ISSUE TITLE
Missing `/` keyboard key?

### ISSUE THREAD

**Issue by EPOCHvoyager** [Supreeeme/extest#22] opened 2024-12-01 22:59 UTC
![image](https://github.com/user-attachments/assets/45d41f02-97c5-476c-bbde-deef49b198ab)

Under GNOME, I am unable to type either `/` or `?` with the Steam OSK. This is under `bazzite-gnome`.

**Comment by Supreeeme** [comment] 2024-12-18 02:08
Dupe of #9

**Closed as not planned by Supreeeme** 2024-12-18 02:08 UTC
